spring:
  application:
    name: docstack

  data:
    mongodb:
      uri: mongodb://localhost:27017/appdb

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://full-mastodon-46.clerk.accounts.dev

clerk:
  issuer: ${CLERK_ISSUER}
  jwks-url: ${CLERK_JWKS_URL}
  secret-key: ${CLERK_SECRET_KEY}


logging:
  level:
    org.springframework.security: DEBUG

app:
  r2:
    account-id: ${R2_ACCOUNT_ID}
    access-key-id: ${R2_ACCESS_KEY_ID}
    secret-access-key: ${R2_SECRET_ACCESS_KEY}
    bucket: ${R2_BUCKET}
    public-base-url: ${R2_PUBLIC_BASE_URL}